# Generated by Django 4.0.6 on 2022-08-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KanalTable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(verbose_name='Заказ №')),
                ('cost_usd', models.DecimalField(decimal_places=65535, max_digits=65535, verbose_name='Стоимость $')),
                ('cost_rub', models.DecimalField(decimal_places=65535, max_digits=65535, verbose_name='Стоимость ₽')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
            ],
            options={
                'db_table': 'kanal_table',
                'managed': False,
            },
        ),
    ]
