# Generated by Django 4.0.6 on 2022-08-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanal_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanaltable',
            options={'managed': False, 'verbose_name': 'Таблица', 'verbose_name_plural': 'Таблица'},
        ),
    ]
